graph TD
    billing_usp_searchaccountsby[billing.usp_searchaccountsby]
    billing_usp_searchaccountsby_updated[billing.usp_searchaccountsby_updated]
    billing_usp_searchaccountsby_excel_export[billing.usp_searchaccountsby_excel_export] --> billing_usp_searchaccountsby[billing.usp_searchaccountsby]
    billing_usp_searchaccountsby_excel_export[billing.usp_searchaccountsby_excel_export] --> billing_usp_searchaccountsby_updated[billing.usp_searchaccountsby_updated]