graph TD
    billing_usp_turnoffmeterbymeterseqid[billing.usp_turnoffmeterbymeterseqid]
    billing_usp_turnoffaccountandrelatedmeters[billing.usp_turnoffaccountandrelatedmeters] --> billing_usp_turnoffmeterbymeterseqid[billing.usp_turnoffmeterbymeterseqid]