graph TD
    coned_usp_validation_checkedtransformeddata[coned.usp_validation_checkedtransformeddata]
    coned_usp_upload_17_transferpreprocesseddataintogasschematables[coned.usp_upload_17_transferpreprocesseddataintogasschematables] --> coned_usp_validation_checkedtransformeddata[coned.usp_validation_checkedtransformeddata]