graph TD
    dbo_master[dbo.master]
    crisnationalgridwest_usp_exportextracteddatatoflatfileformatforeccs[crisnationalgridwest.usp_exportextracteddatatoflatfileformatforeccs] --> dbo_master[dbo.master]