graph TD
    dbo_aspnet_personalization_getapplicationid[dbo.aspnet_personalization_getapplicationid]
    dbo_aspnet_personalizationadministration_deleteallstate[dbo.aspnet_personalizationadministration_deleteallstate] --> dbo_aspnet_personalization_getapplicationid[dbo.aspnet_personalization_getapplicationid]