graph TD
    dbo_aspnet_applications_createapplication[dbo.aspnet_applications_createapplication]
    dbo_aspnet_roles_createrole[dbo.aspnet_roles_createrole] --> dbo_aspnet_applications_createapplication[dbo.aspnet_applications_createapplication]