graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_lookup_getaccountdetailfortariffreport_updated[report.usp_lookup_getaccountdetailfortariffreport_updated] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]