graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_lookupagencyandfacilityinformation[report.usp_lookupagencyandfacilityinformation] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]