graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_lookup_accountinformation_upgrade[report.usp_lookup_accountinformation_upgrade] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]