graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_accountinformationbyaccountnumber[report.usp_accountinformationbyaccountnumber] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]