graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_published_getmonthlyagencyfacilitydata2[report.usp_published_getmonthlyagencyfacilitydata2] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]