graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_published_corereportreportaccountlevel[report.usp_published_corereportreportaccountlevel] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]