graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_published_getmonthlyagencyfacilitydata[report.usp_published_getmonthlyagencyfacilitydata] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]