graph TD
    contentmanagement_usp_insertdocumentendofmonth[contentmanagement.usp_insertdocumentendofmonth]
    scheduler_usp_archivereport[scheduler.usp_archivereport] --> contentmanagement_usp_insertdocumentendofmonth[contentmanagement.usp_insertdocumentendofmonth]