import os
import shutil
import json
from datetime import datetime
import subprocess


def wipe_output_directory(output_dir: str):
  """
  Wipe the existing output directory by deleting its contents, and recreate it.

  :param output_dir: The directory to wipe and recreate.
  """
  if os.path.exists(output_dir):
    shutil.rmtree(output_dir)  # Delete the directory and all its contents
  os.makedirs(output_dir, exist_ok=True)  # Recreate the directory
  print(f"Output directory wiped and recreated: {output_dir}")


def load_generated_files(output_dir: str):
  """
  Load the files generated by ExecutionFlowDiagramGenerator.py.

  :param output_dir: Directory where the output files are stored.
  :return: Dictionary containing Mermaid schema diagrams, Excel summary, and other metadata.
  """
  files = {}

  # Path for schema Mermaid diagrams
  schema_dir = os.path.join(output_dir, "schemas")
  if os.path.exists(schema_dir):
    files["schemas"] = [
      os.path.join(schema_dir, file)
      for file in os.listdir(schema_dir) if file.endswith(".mmd")
    ]

  # Path for the Excel summary
  excel_file = os.path.join(output_dir, "procedure_depth_summary.xlsx")
  if os.path.exists(excel_file):
    files["excel_summary"] = excel_file

  # Path for the call graph CSV
  csv_file = os.path.join(output_dir, "call_graph.csv")
  if os.path.exists(csv_file):
    files["csv"] = csv_file

  return files


def convert_mermaid_to_png(mermaid_file: str, output_dir: str):
  """
  Convert a Mermaid diagram (.mmd file) to PNG format using the Mermaid CLI tool.

  :param mermaid_file: Path to the Mermaid file.
  :param output_dir: Directory to save the PNG image.
  :return: Path to the PNG file.
  """
  png_filename = os.path.splitext(os.path.basename(mermaid_file))[0] + ".png"
  png_filepath = os.path.join(output_dir, png_filename)

  try:
    # Run the mmdc command to generate a PNG file
    subprocess.run(["mmdc", "-i", mermaid_file, "-o", png_filepath], check=True)
    print(f"Converted {mermaid_file} to PNG: {png_filepath}")
    return png_filepath
  except subprocess.CalledProcessError as e:
    print(f"Failed to generate PNG for {mermaid_file}: {e}")
    return None


def generate_adf_with_page_properties(file_name: str, file_type: str, schema_name: str, png_image_path: str):
  """
  Generate an ADF document that includes page properties and additional content.

  :param file_name: Name of the file.
  :param file_type: Type of content represented by the file (e.g., Mermaid Diagram, Excel Summary, etc.).
  :param schema_name: The name of the schema related to the file.
  :param png_image_path: Path to the PNG image file to embed in the Confluence page.
  :return: ADF document with page properties and an embedded image.
  """
  generated_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

  # Generate page properties table
  page_properties = {
    "type": "bodiedExtension",
    "attrs": {
      "extensionType": "com.atlassian.confluence.macro.core",
      "extensionKey": "details",
      "parameters": {
        "macroParams": {
          "hidden": {"value": "true"}
        },
        "macroMetadata": {
          "schemaVersion": {"value": "1"},
          "title": "Page Properties"
        }
      }
    },
    "content": [
      {
        "type": "table",
        "attrs": {
          "isNumberColumnEnabled": False,
          "layout": "default"
        },
        "content": [
          {
            "type": "tableRow",
            "content": [
              {
                "type": "tableHeader",
                "content": [
                  {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "File Name"}]
                  }
                ]
              },
              {
                "type": "tableCell",
                "content": [
                  {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": file_name}]
                  }
                ]
              }
            ]
          },
          {
            "type": "tableRow",
            "content": [
              {
                "type": "tableHeader",
                "content": [
                  {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "File Type"}]
                  }
                ]
              },
              {
                "type": "tableCell",
                "content": [
                  {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": file_type}]
                  }
                ]
              }
            ]
          },
          {
            "type": "tableRow",
            "content": [
              {
                "type": "tableHeader",
                "content": [
                  {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "Schema"}]
                  }
                ]
              },
              {
                "type": "tableCell",
                "content": [
                  {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": schema_name}]
                  }
                ]
              }
            ]
          },
          {
            "type": "tableRow",
            "content": [
              {
                "type": "tableHeader",
                "content": [
                  {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "Generated Date"}]
                  }
                ]
              },
              {
                "type": "tableCell",
                "content": [
                  {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": generated_date}]
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }

  # Combine page properties with an embedded image
  adf_document = {
    "version": 1,
    "type": "doc",
    "content": [
      page_properties,
      {
        "type": "mediaSingle",
        "attrs": {
          "layout": "center"
        },
        "content": [
          {
            "type": "media",
            "attrs": {
              "type": "file",
              "collection": "confluence-attachments",
              "id": png_image_path
            }
          }
        ]
      }
    ]
  }
  return adf_document


def generate_metadata(file_name: str, file_type: str, schema_name: str):
  """
  Generate metadata for the associated file content.

  :param file_name: Name of the file.
  :param file_type: Type of content represented by the file.
  :param schema_name: The name of the schema related to the file.
  :return: Dictionary containing metadata for the file.
  """
  return {
    "title": f"{schema_name} - {file_name}",
    "type": file_type,
    "schema": schema_name,
    "generated_date": datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    "description": f"This Confluence page represents the {file_type} for schema '{schema_name}'."
  }


def create_confluence_pages_with_png(output_dir: str, confluence_output_dir: str):
  """
  Generate Confluence ADF JSON pages with PNG diagrams and metadata.

  :param output_dir: Directory where output files (Mermaid diagrams) are stored.
  :param confluence_output_dir: Directory to store Confluence ADF JSON pages with PNG diagrams.
  """
  wipe_output_directory(confluence_output_dir)  # Wipe output directory

  files = load_generated_files(output_dir)
  if not files:
    print("No files found in the output directory.")
    return

  # Process each schema diagram
  for schema_file in files.get("schemas", []):
    schema_name = os.path.splitext(os.path.basename(schema_file))[0]
    png_file_path = convert_mermaid_to_png(schema_file, confluence_output_dir)

    if png_file_path:
      # Generate ADF content
      adf_with_properties = generate_adf_with_page_properties(
        file_name=os.path.basename(png_file_path),
        file_type="Schema Diagram (PNG)",
        schema_name=schema_name,
        png_image_path=png_file_path
      )

      # Save the ADF JSON file
      adf_file = os.path.join(confluence_output_dir, f"{schema_name}.json")
      with open(adf_file, "w", encoding="utf-8") as f:
        json.dump(adf_with_properties, f, indent=2, ensure_ascii=False)
      print(f"Generated Confluence ADF for schema: {schema_name}")

      # Generate and save metadata
      metadata = generate_metadata(
        file_name=os.path.basename(png_file_path),
        file_type="Schema Diagram (PNG)",
        schema_name=schema_name
      )
      metadata_file = os.path.join(confluence_output_dir, f"{schema_name}_metadata.json")
      with open(metadata_file, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)
      print(f"Generated metadata for schema: {schema_name}")


def main():
  output_dir = "./output"  # Directory where execution flow generator output files are stored
  confluence_output_dir = "./confluence_docs/sp_diagrams"  # Directory for Confluence ADF JSON files

  create_confluence_pages_with_png(output_dir, confluence_output_dir)

  print("\nConfluence ADF pages with PNG diagrams created successfully.")
  print(f"Files are located in: {confluence_output_dir}")


if __name__ == "__main__":
  main()
