graph TD
    dbo_finalcheckofbackbillingattheaccountlevel[dbo.finalcheckofbackbillingattheaccountlevel]
    batch_usp_process_main_checknobackbills[batch.usp_process_main_checknobackbills] --> dbo_finalcheckofbackbillingattheaccountlevel[dbo.finalcheckofbackbillingattheaccountlevel]