graph TD
    common_copyconedexchangedatatocommon[common.copyconedexchangedatatocommon]
    dbo_this[dbo.this]
    common_usp_coned_handleexchangedataissues[common.usp_coned_handleexchangedataissues] --> common_copyconedexchangedatatocommon[common.copyconedexchangedatatocommon]
    common_usp_coned_handleexchangedataissues[common.usp_coned_handleexchangedataissues] --> dbo_this[dbo.this]