graph TD
    dbo_aspnet_applications_createapplication[dbo.aspnet_applications_createapplication]
    dbo_aspnet_paths_createpath[dbo.aspnet_paths_createpath]
    dbo_aspnet_users_createuser[dbo.aspnet_users_createuser]
    dbo_aspnet_personalizationperuser_setpagesettings[dbo.aspnet_personalizationperuser_setpagesettings] --> dbo_aspnet_applications_createapplication[dbo.aspnet_applications_createapplication]
    dbo_aspnet_personalizationperuser_setpagesettings[dbo.aspnet_personalizationperuser_setpagesettings] --> dbo_aspnet_paths_createpath[dbo.aspnet_paths_createpath]
    dbo_aspnet_personalizationperuser_setpagesettings[dbo.aspnet_personalizationperuser_setpagesettings] --> dbo_aspnet_users_createuser[dbo.aspnet_users_createuser]