graph TD
    dbo_aspnet_applications_createapplication[dbo.aspnet_applications_createapplication]
    dbo_aspnet_users_createuser[dbo.aspnet_users_createuser]
    dbo_aspnet_profile_setproperties[dbo.aspnet_profile_setproperties] --> dbo_aspnet_applications_createapplication[dbo.aspnet_applications_createapplication]
    dbo_aspnet_profile_setproperties[dbo.aspnet_profile_setproperties] --> dbo_aspnet_users_createuser[dbo.aspnet_users_createuser]