graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_accountlevelbillinghistory[report.usp_accountlevelbillinghistory] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]