graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_published_usageanddemanddeviationreportdash[report.usp_published_usageanddemanddeviationreportdash] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]