graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_published_partiallookupcurrentaccount[report.usp_published_partiallookupcurrentaccount] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]