graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_published_energycomparisonreportcitywide_updated[report.usp_published_energycomparisonreportcitywide_updated] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]