graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_getallpropertieslinkedtoafacility[report.usp_getallpropertieslinkedtoafacility] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]