graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_dataexport_accountadjustment[report.usp_dataexport_accountadjustment] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]