graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_monthlyagencydatabyenergytype[report.usp_monthlyagencydatabyenergytype] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]