graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_published_lookuptotaldollarsbtusandrunningtotalco2byenergytypethreefiscalyears_updated[report.usp_published_lookuptotaldollarsbtusandrunningtotalco2byenergytypethreefiscalyears_updated] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]