graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_activeaccountsbyagency_upgrade[report.usp_activeaccountsbyagency_upgrade] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]