graph TD
    audit_usp_addreportusagelog[audit.usp_addreportusagelog]
    report_usp_published_lookuptotaldollarsbtusandrunningtotalco2byenergytype[report.usp_published_lookuptotaldollarsbtusandrunningtotalco2byenergytype] --> audit_usp_addreportusagelog[audit.usp_addreportusagelog]